# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=200)),
                ('sap_id', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lender',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lender',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='safety_deposit',
            field=models.IntegerField(),
        ),
    ]
