# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20200201_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
